"""SES email delivery for Research rAIdar digests."""

import os
import textwrap
from datetime import date
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import boto3

SES_SENDER    = os.environ["SES_SENDER"]
SES_RECIPIENT = os.environ["SES_RECIPIENT"]
SES_REGION    = os.environ.get("SES_REGION", os.environ.get("AWS_REGION", "us-east-1"))
CONFIG_ENV    = os.environ.get("CONFIG_ENV", "dev")
CONFIG_BUCKET = f"research-raidar-{CONFIG_ENV}"
LOGO_S3_KEY   = "research-raidar-logo.png"

# ── Logo cache (warm Lambda reuse) ────────────────────────────────────────────

_logo_bytes: bytes | None = None


def _load_logo() -> bytes | None:
    """Load logo from S3; cached for the lifetime of a warm container."""
    global _logo_bytes
    if _logo_bytes is None:
        try:
            s3 = boto3.client("s3")
            _logo_bytes = s3.get_object(Bucket=CONFIG_BUCKET, Key=LOGO_S3_KEY)["Body"].read()
        except Exception:
            _logo_bytes = b""   # sentinel: tried and failed
    return _logo_bytes or None


# ── Public interface ──────────────────────────────────────────────────────────

def send_digest(top_papers: list[dict], total_fetched: int, categories: list[str]) -> None:
    """Format and send the digest email."""
    subject, html = format_digest(top_papers, total_fetched, categories)
    _send(subject, html)


def format_digest(top_papers: list[dict], total_fetched: int, categories: list[str]) -> tuple[str, str]:
    """Return (subject, html_body)."""
    today   = date.today().strftime("%a %b %-d")
    subject = f"Research rAIdar {today} — top {len(top_papers)} of {total_fetched} papers"

    rows = ""
    for i, p in enumerate(top_papers, 1):
        cats = " · ".join(p["categories"][:3])
        rows += textwrap.dedent(f"""
            <tr>
              <td style="padding:14px 0;border-bottom:1px solid #eee;vertical-align:top">
                <div style="display:flex;align-items:baseline;gap:10px">
                  <span style="font-size:22px;font-weight:600;color:#1a1a1a;min-width:28px">{i}</span>
                  <div>
                    <a href="{p['url']}" style="font-size:15px;font-weight:600;color:#0066cc;text-decoration:none">
                      {p['title']}
                    </a>
                    <div style="font-size:12px;color:#888;margin-top:3px">{p['authors']}</div>
                    <div style="font-size:13px;color:#444;margin-top:6px">{p['reason']}</div>
                    <div style="margin-top:6px">
                      <span style="background:#f0f4ff;color:#3355aa;font-size:11px;
                                   padding:2px 8px;border-radius:4px;font-weight:500">
                        Score {int(p['score'])}
                      </span>
                      <span style="color:#aaa;font-size:11px;margin-left:8px">{cats}</span>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
        """)

    html = textwrap.dedent(f"""
        <!DOCTYPE html>
        <html>
        <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
                     max-width:640px;margin:0 auto;padding:24px;color:#1a1a1a">
          <img src="cid:research-raidar-logo" alt="Research rAIdar"
               style="max-height:56px;display:block;margin-bottom:4px;">
          <p style="margin:0 0 20px;color:#888;font-size:13px">
            {today} · {len(top_papers)} papers · scored from {total_fetched} fetched
          </p>
          <table style="width:100%;border-collapse:collapse">
            {rows}
          </table>
          <p style="font-size:11px;color:#ccc;margin-top:24px">
            Categories: {', '.join(categories)}
          </p>
          <div style="text-align:center;color:#999;font-size:12px;margin-top:40px;padding-top:20px;border-top:1px solid #eee">
            Designed by Michael Dinsmore &bull; Generated by StackBio Research rAIdar &bull; Powered by AWS Bedrock
          </div>
        </body>
        </html>
    """)

    return subject, html


# ── SES delivery ──────────────────────────────────────────────────────────────

def _send(subject: str, html_body: str) -> None:
    ses = boto3.client("ses", region_name=SES_REGION)

    # multipart/related allows inline image attachments referenced by cid:
    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"]    = SES_SENDER
    msg["To"]      = SES_RECIPIENT

    msg_alt = MIMEMultipart("alternative")
    msg.attach(msg_alt)
    msg_alt.attach(MIMEText(html_body, "html"))

    logo = _load_logo()
    if logo:
        logo_mime = MIMEImage(logo, "png")
        logo_mime.add_header("Content-ID", "<research-raidar-logo>")
        logo_mime.add_header("Content-Disposition", "inline", filename="research-raidar-logo.png")
        msg.attach(logo_mime)

    ses.send_raw_email(
        Source=SES_SENDER,
        Destinations=[SES_RECIPIENT],
        RawMessage={"Data": msg.as_string()},
    )
